/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.supplier;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Supplier;
import model.SupplierDirectory;
import ui.LoginScreen;

/**
 *
 * @author ornellabajou
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    Supplier supplier;
    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    public SupplierWorkAreaJPanel(JPanel mainWorkArea, Supplier supplier) {
        initComponents();
        
        this.mainWorkArea = mainWorkArea;
        this.supplier= supplier;
        if(supplier != null) lblWelcome.setText ("Welcome to Lab4, " + supplier.getSupplierName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuBarJPanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnManageProductCatalog = new javax.swing.JButton();
        btnSuppliersProfile = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        workAreaJPanel = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        lblWelcome.setText("Welcome to Lab4");

        btnManageProductCatalog.setText("Product Catalog");
        btnManageProductCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProductCatalogActionPerformed(evt);
            }
        });

        btnSuppliersProfile.setText("Supplier Profile");

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarJPanelLayout = new javax.swing.GroupLayout(menuBarJPanel);
        menuBarJPanel.setLayout(menuBarJPanelLayout);
        menuBarJPanelLayout.setHorizontalGroup(
            menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageProductCatalog)
                .addGap(66, 66, 66)
                .addComponent(btnSuppliersProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addContainerGap())
        );
        menuBarJPanelLayout.setVerticalGroup(
            menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(btnManageProductCatalog)
                    .addComponent(btnSuppliersProfile)
                    .addComponent(btnLogOut))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(menuBarJPanel);

        workAreaJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProductCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProductCatalogActionPerformed
        // TODO add your handling code here:
                                                                                                                     
                                                               
        if (supplier == null) {
        JOptionPane.showMessageDialog(this, "No supplier is associated. Please log in again.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        ManageProductCatalogJPanel manageProductCatalogJPanel = new ManageProductCatalogJPanel(mainWorkArea, supplier);
        mainWorkArea.add("ManageProductCatalogJPanel", manageProductCatalogJPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);





        
    }//GEN-LAST:event_btnManageProductCatalogActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        
        mainWorkArea.remove(this);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
        
    }//GEN-LAST:event_btnLogOutActionPerformed
    public String toString(){
        return "Supplier";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageProductCatalog;
    private javax.swing.JButton btnSuppliersProfile;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel menuBarJPanel;
    private javax.swing.JPanel workAreaJPanel;
    // End of variables declaration//GEN-END:variables
}
