/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import javax.swing.JPanel;
import model.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Supplier;
import model.SupplierDirectory;
import ui.admin.AdminWorkAreaJPanel;
import ui.supplier.SupplierWorkAreaJPanel;
/**
 *
 * @author ornellabajou
 */
public class LoginScreen extends javax.swing.JPanel {
    private JPanel workArea;
    private SupplierDirectory supplierDirectory;
    private Supplier selectedSupplier = null;

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen(JPanel workArea, SupplierDirectory supplierDirectory) {
    initComponents();
    this.workArea = workArea;
    this.supplierDirectory = supplierDirectory;

 

    populateRoleCombo();
    populateSupplierCombo();
    updateSupplierVisibility();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        workAreaJPanel = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        cmbRoles = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        cmbSuppliers = new javax.swing.JComboBox<>();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTitle.setText("              Welcome to Lab4");

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topJPanelLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(topJPanel);

        lblRole.setText("Choose Role");

        lblSupplier.setText("Select Supplier");

        cmbRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Supplier" }));
        cmbRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolesActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        cmbSuppliers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BestBuy", "MustBuy" }));
        cmbSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSuppliersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workAreaJPanelLayout = new javax.swing.GroupLayout(workAreaJPanel);
        workAreaJPanel.setLayout(workAreaJPanelLayout);
        workAreaJPanelLayout.setHorizontalGroup(
            workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaJPanelLayout.createSequentialGroup()
                .addGroup(workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workAreaJPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbRoles, 0, 154, Short.MAX_VALUE)
                            .addComponent(cmbSuppliers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(workAreaJPanelLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnLogin)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        workAreaJPanelLayout.setVerticalGroup(
            workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaJPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(cmbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplier)
                    .addComponent(cmbSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnLogin)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(workAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
                                               
        String selectedRole = (String) cmbRoles.getSelectedItem();

        if (selectedRole == null) {
        JOptionPane.showMessageDialog(this, "Please select a role", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }

        if (selectedRole.equals("Administrator")) {
        AdminWorkAreaJPanel adminPanel = new AdminWorkAreaJPanel(workArea, supplierDirectory);
        workArea.add("AdminWorkAreaJPanel", adminPanel);
        } 
        else if (selectedRole.equals("Supplier")) {
            if (selectedSupplier == null) {
            JOptionPane.showMessageDialog(this, "Please select a supplier", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        SupplierWorkAreaJPanel supplierPanel = new SupplierWorkAreaJPanel(workArea, selectedSupplier);
        workArea.add("SupplierWorkAreaJPanel", supplierPanel);
        }

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        

        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cmbRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolesActionPerformed
        // TODO add your handling code here:
        updateSupplierVisibility();
        
    }//GEN-LAST:event_cmbRolesActionPerformed

    private void cmbSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSuppliersActionPerformed
        // TODO add your handling code here:
        String selectedName = (String) cmbSuppliers.getSelectedItem();
        if (selectedName != null) {
        selectedSupplier = supplierDirectory.getSupplierList()
                .stream()
                .filter(s -> s.getSupplierName().equals(selectedName))
                .findFirst()
                .orElse(null);
            }
    }//GEN-LAST:event_cmbSuppliersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbRoles;
    private javax.swing.JComboBox<String> cmbSuppliers;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel workAreaJPanel;
    // End of variables declaration//GEN-END:variables

    private void populateRoleCombo() {
        cmbRoles.removeAllItems();
        cmbRoles.addItem("Administrator");
        cmbRoles.addItem("Supplier");
    
    }

    public void populateSupplierCombo() {
        cmbSuppliers.removeAllItems();
        for (Supplier s : supplierDirectory.getSupplierList()) {
        cmbSuppliers.addItem(s.getSupplierName()); // only names
        }
    }
    
    private void updateSupplierVisibility(){
        String selectedRole = (String) cmbRoles.getSelectedItem();
        boolean supplierRole = selectedRole != null && selectedRole.equals("Supplier");
        lblSupplier.setVisible(supplierRole);
        cmbSuppliers.setVisible(supplierRole);
        if (!supplierRole) selectedSupplier = null;
   }
}